### ISSUE TITLE
mount folder from host

### ISSUE THREAD

**Issue by Baxalax** [cardinalby/chrome-remote-desktop-image#2]
Hello, thx for this docker image. Am trying to download a file via firefox, which works, but how do I get the file from docker storage to my real storage of NAS? Lets say I want to access the file via Synology File Station.
I was not able to mount folder in image settings - perhaps I dont know how exactly :D 

thx for your answer

**Comment by cardinalby** [comment]
I haven't try, but I suppose you should be able to mount a **volume** on Volume tab in Advanced Settings of Create Container dialog

**Comment by Baxalax** [comment]
I have tried that, but maybe I do enter wrong paths for docker mount
folder, it doesn't work. What would be the right path name for download
folder inside of Ubuntu?

Dne po 3. 4. 2023 19:25 uživatel Cardinal ***@***.***> napsal:

**Comment by cardinalby** [comment]
Try using `/home/myuser/Downloads` path inside the container, it's used by Firefox for downloads
It can be tricky because of permissions, user inside the container has **uid=1000, gid=1000** so you need to mount a directory with the same owner from your Synology.

To do it, you need to SSH to the Synology, execute smth like
```sh
sudo chown 1000 path/to/dir
```

Another way would be setting uid/gid on container run, but it's not implemented in the image (PRs are welcome)
